import os
from pathlib import Path

def create_project_structure():
    # Define the project structure as a nested dictionary
    project_structure = {
        'ecommerce-platform-pro': {
            '.env.local': None,
            '.env.example': None,
            '.gitignore': None,
            '.eslintrc.json': None,
            '.prettierrc': None,
            'next.config.js': None,
            'package.json': None,
            'tailwind.config.js': None,
            'tsconfig.json': None,
            'components.json': None,
            'middleware.ts': None,
            'README.md': None,
            'LICENSE.md': None,
            'CHANGELOG.md': None,
            'DOCUMENTATION.md': None,
            'setup-wizard.js': None,
            'app': {
                'globals.css': None,
                'layout.tsx': None,
                'page.tsx': None,
                'loading.tsx': None,
                'error.tsx': None,
                'not-found.tsx': None,
                'manifest.ts': None,
                'robots.ts': None,
                'sitemap.ts': None,
                '(setup)': {
                    'layout.tsx': None,
                    'setup': {
                        'page.tsx': None,
                        'license': {'page.tsx': None},
                        'database': {'page.tsx': None},
                        'admin': {'page.tsx': None},
                        'store': {'page.tsx': None},
                        'complete': {'page.tsx': None},
                    },
                },
                '(auth)': {
                    'layout.tsx': None,
                    'login': {'page.tsx': None},
                    'register': {'page.tsx': None},
                    'forgot-password': {'page.tsx': None},
                    'reset-password': {'[token]': {'page.tsx': None}},
                    'verify-email': {'[token]': {'page.tsx': None}},
                },
                '(storefront)': {
                    'layout.tsx': None,
                    'shop': {
                        'page.tsx': None,
                        'category': {'[slug]': {'page.tsx': None}},
                        'brand': {'[slug]': {'page.tsx': None}},
                        'product': {'[slug]': {'page.tsx': None}},
                    },
                    'cart': {'page.tsx': None},
                    'checkout': {
                        'page.tsx': None,
                        'shipping': {'page.tsx': None},
                        'payment': {'page.tsx': None},
                        'review': {'page.tsx': None},
                        'success': {'page.tsx': None},
                    },
                    'account': {
                        'page.tsx': None,
                        'profile': {'page.tsx': None},
                        'orders': {'page.tsx': None, '[id]': {'page.tsx': None}},
                        'addresses': {'page.tsx': None},
                        'wishlist': {'page.tsx': None},
                        'settings': {'page.tsx': None},
                    },
                    'search': {'page.tsx': None},
                    'pages': {
                        'about': {'page.tsx': None},
                        'contact': {'page.tsx': None},
                        'privacy': {'page.tsx': None},
                        'terms': {'page.tsx': None},
                        'faq': {'page.tsx': None},
                    },
                    'loading.tsx': None,
                },
                '(admin)': {
                    'layout.tsx': None,
                    'loading.tsx': None,
                    'admin': {
                        'page.tsx': None,
                        'users': {
                            'page.tsx': None,
                            'create': {'page.tsx': None},
                            '[id]': {'page.tsx': None, 'edit': {'page.tsx': None}},
                        },
                        'products': {
                            'page.tsx': None,
                            'create': {'page.tsx': None},
                            'import': {'page.tsx': None},
                            'export': {'page.tsx': None},
                            '[id]': {'page.tsx': None, 'edit': {'page.tsx': None}},
                        },
                        'categories': {
                            'page.tsx': None,
                            'create': {'page.tsx': None},
                            '[id]': {'page.tsx': None, 'edit': {'page.tsx': None}},
                        },
                        'brands': {
                            'page.tsx': None,
                            'create': {'page.tsx': None},
                            '[id]': {'page.tsx': None, 'edit': {'page.tsx': None}},
                        },
                        'attributes': {
                            'page.tsx': None,
                            'create': {'page.tsx': None},
                        },
                        'orders': {
                            'page.tsx': None,
                            '[id]': {'page.tsx': None},
                            'bulk-actions': {'page.tsx': None},
                        },
                        'customers': {
                            'page.tsx': None,
                            '[id]': {'page.tsx': None, 'orders': {'page.tsx': None}},
                        },
                        'inventory': {
                            'page.tsx': None,
                            'low-stock': {'page.tsx': None},
                            'adjustments': {'page.tsx': None},
                        },
                        'analytics': {
                            'page.tsx': None,
                            'sales': {'page.tsx': None},
                            'products': {'page.tsx': None},
                            'customers': {'page.tsx': None},
                        },
                        'reports': {
                            'page.tsx': None,
                            'sales': {'page.tsx': None},
                            'inventory': {'page.tsx': None},
                            'customers': {'page.tsx': None},
                            'taxes': {'page.tsx': None},
                        },
                        'marketing': {
                            'page.tsx': None,
                            'coupons': {
                                'page.tsx': None,
                                'create': {'page.tsx': None},
                                '[id]': {'page.tsx': None, 'edit': {'page.tsx': None}},
                            },
                            'reviews': {'page.tsx': None, '[id]': {'page.tsx': None}},
                        },
                        'settings': {
                            'page.tsx': None,
                            'general': {'page.tsx': None},
                            'store': {'page.tsx': None},
                            'shipping': {
                                'page.tsx': None,
                                'zones': {'page.tsx': None, 'create': {'page.tsx': None}},
                                'methods': {'page.tsx': None, 'create': {'page.tsx': None}},
                            },
                            'taxes': {
                                'page.tsx': None,
                                'rates': {'page.tsx': None, 'create': {'page.tsx': None}},
                            },
                            'payments': {'page.tsx': None},
                            'email': {'page.tsx': None, 'templates': {'page.tsx': None}},
                            'seo': {'page.tsx': None},
                            'security': {'page.tsx': None},
                            'advanced': {'page.tsx': None},
                        },
                        'addons': {
                            'page.tsx': None,
                            'marketplace': {'page.tsx': None},
                            'installed': {'page.tsx': None},
                            'upload': {'page.tsx': None},
                            '[addon]': {
                                'page.tsx': None,
                                'settings': {'page.tsx': None},
                                'logs': {'page.tsx': None},
                                'uninstall': {'page.tsx': None},
                            },
                        },
                    },
                },
                'api': {
                    'setup': {
                        'verify-license': {'route.ts': None},
                        'check-database': {'route.ts': None},
                        'create-database': {'route.ts': None},
                        'create-admin': {'route.ts': None},
                        'configure-store': {'route.ts': None},
                        'complete': {'route.ts': None},
                    },
                    'auth': {
                        '[...nextauth]': {'route.ts': None},
                        'register': {'route.ts': None},
                        'login': {'route.ts': None},
                        'logout': {'route.ts': None},
                        'forgot-password': {'route.ts': None},
                        'reset-password': {'route.ts': None},
                        'verify-email': {'route.ts': None},
                        'me': {'route.ts': None},
                    },
                    'users': {
                        'route.ts': None,
                        'profile': {'route.ts': None},
                        'avatar': {'route.ts': None},
                        '[id]': {
                            'route.ts': None,
                            'activate': {'route.ts': None},
                            'orders': {'route.ts': None},
                        },
                    },
                    'products': {
                        'route.ts': None,
                        'search': {'route.ts': None},
                        'featured': {'route.ts': None},
                        'trending': {'route.ts': None},
                        'import': {'route.ts': None},
                        'export': {'route.ts': None},
                        '[id]': {
                            'route.ts': None,
                            'images': {'route.ts': None},
                            'variants': {'route.ts': None},
                            'reviews': {'route.ts': None},
                            'related': {'route.ts': None},
                        },
                    },
                    'categories': {
                        'route.ts': None,
                        'tree': {'route.ts': None},
                        '[id]': {'route.ts': None, 'products': {'route.ts': None}},
                    },
                    'brands': {
                        'route.ts': None,
                        '[id]': {'route.ts': None, 'products': {'route.ts': None}},
                    },
                    'attributes': {
                        'route.ts': None,
                        '[id]': {'route.ts': None},
                    },
                    'orders': {
                        'route.ts': None,
                        'stats': {'route.ts': None},
                        '[id]': {
                            'route.ts': None,
                            'status': {'route.ts': None},
                            'cancel': {'route.ts': None},
                            'refund': {'route.ts': None},
                            'tracking': {'route.ts': None},
                        },
                    },
                    'cart': {
                        'route.ts': None,
                        'add': {'route.ts': None},
                        'update': {'route.ts': None},
                        'remove': {'route.ts': None},
                        'clear': {'route.ts': None},
                        'count': {'route.ts': None},
                    },
                    'wishlist': {
                        'route.ts': None,
                        'add': {'route.ts': None},
                        'remove': {'route.ts': None},
                        'clear': {'route.ts': None},
                    },
                    'checkout': {
                        'calculate': {'route.ts': None},
                        'validate': {'route.ts': None},
                        'process': {'route.ts': None},
                    },
                    'shipping': {
                        'zones': {'route.ts': None, '[id]': {'route.ts': None}},
                        'methods': {'route.ts': None, '[id]': {'route.ts': None}},
                        'calculate': {'route.ts': None},
                    },
                    'taxes': {
                        'rates': {'route.ts': None, '[id]': {'route.ts': None}},
                        'calculate': {'route.ts': None},
                    },
                    'coupons': {
                        'route.ts': None,
                        'validate': {'route.ts': None},
                        'apply': {'route.ts': None},
                        '[id]': {'route.ts': None},
                    },
                    'reviews': {
                        'route.ts': None,
                        '[id]': {
                            'route.ts': None,
                            'approve': {'route.ts': None},
                            'reject': {'route.ts': None},
                        },
                    },
                    'analytics': {
                        'dashboard': {'route.ts': None},
                        'sales': {'route.ts': None},
                        'products': {'route.ts': None},
                        'customers': {'route.ts': None},
                        'reports': {'route.ts': None},
                    },
                    'settings': {
                        'route.ts': None,
                        'general': {'route.ts': None},
                        'store': {'route.ts': None},
                        'email': {'route.ts': None},
                        'seo': {'route.ts': None},
                        'security': {'route.ts': None},
                    },
                    'uploads': {
                        'images': {'route.ts': None},
                        'files': {'route.ts': None},
                        'avatars': {'route.ts': None},
                        'cleanup': {'route.ts': None},
                    },
                    'search': {
                        'products': {'route.ts': None},
                        'suggestions': {'route.ts': None},
                        'autocomplete': {'route.ts': None},
                    },
                    'addons': {
                        'route.ts': None,
                        'marketplace': {'route.ts': None, '[addon]': {'route.ts': None}},
                        'upload': {'route.ts': None},
                        'install': {'route.ts': None},
                        'uninstall': {'route.ts': None},
                        'activate': {'route.ts': None},
                        'deactivate': {'route.ts': None},
                        'validate': {'route.ts': None},
                        'settings': {'[addon]': {'route.ts': None}},
                        '[addon]': {
                            'route.ts': None,
                            'webhook': {'route.ts': None},
                            '[...path]': {'route.ts': None},
                        },
                    },
                    'hooks': {
                        'before-order-create': {'route.ts': None},
                        'after-order-create': {'route.ts': None},
                        'before-payment-process': {'route.ts': None},
                        'after-payment-process': {'route.ts': None},
                        'before-product-create': {'route.ts': None},
                        'after-product-create': {'route.ts': None},
                        'before-user-register': {'route.ts': None},
                        'after-user-register': {'route.ts': None},
                        'product-view': {'route.ts': None},
                    },
                    'webhooks': {
                        'stripe': {'route.ts': None},
                        'paypal': {'route.ts': None},
                        '[service]': {'route.ts': None},
                    },
                },
            },
            'components': {
                'ui': {
                    'index.ts': None,
                    'button.tsx': None,
                    'input.tsx': None,
                    'textarea.tsx': None,
                    'select.tsx': None,
                    'checkbox.tsx': None,
                    'radio-group.tsx': None,
                    'switch.tsx': None,
                    'slider.tsx': None,
                    'card.tsx': None,
                    'dialog.tsx': None,
                    'sheet.tsx': None,
                    'dropdown-menu.tsx': None,
                    'form.tsx': None,
                    'label.tsx': None,
                    'table.tsx': None,
                    'tabs.tsx': None,
                    'accordion.tsx': None,
                    'toast.tsx': None,
                    'badge.tsx': None,
                    'progress.tsx': None,
                    'separator.tsx': None,
                    'skeleton.tsx': None,
                    'alert.tsx': None,
                    'avatar.tsx': None,
                    'calendar.tsx': None,
                    'popover.tsx': None,
                    'tooltip.tsx': None,
                },
                'setup': {
                    'index.ts': None,
                    'setup-layout.tsx': None,
                    'license-verification.tsx': None,
                    'database-configuration.tsx': None,
                    'admin-creation.tsx': None,
                    'store-configuration.tsx': None,
                    'installation-progress.tsx': None,
                    'setup-complete.tsx': None,
                },
                'auth': {
                    'index.ts': None,
                    'login-form.tsx': None,
                    'register-form.tsx': None,
                    'forgot-password-form.tsx': None,
                    'reset-password-form.tsx': None,
                    'email-verification.tsx': None,
                    'auth-guard.tsx': None,
                    'role-guard.tsx': None,
                },
                'layout': {
                    'index.ts': None,
                    'storefront': {
                        'index.ts': None,
                        'header.tsx': None,
                        'footer.tsx': None,
                        'navigation.tsx': None,
                        'mobile-menu.tsx': None,
                        'search-bar.tsx': None,
                        'cart-drawer.tsx': None,
                        'breadcrumb.tsx': None,
                    },
                    'admin': {
                        'index.ts': None,
                        'admin-layout.tsx': None,
                        'admin-sidebar.tsx': None,
                        'admin-header.tsx': None,
                        'admin-breadcrumb.tsx': None,
                        'admin-mobile-nav.tsx': None,
                    },
                    'common': {
                        'index.ts': None,
                        'theme-provider.tsx': None,
                        'loading-spinner.tsx': None,
                        'error-boundary.tsx': None,
                        'not-found.tsx': None,
                    },
                },
                'storefront': {
                    'index.ts': None,
                    'product': {
                        'index.ts': None,
                        'product-card.tsx': None,
                        'product-grid.tsx': None,
                        'product-list.tsx': None,
                        'product-details.tsx': None,
                        'product-gallery.tsx': None,
                        'product-reviews.tsx': None,
                        'product-variants.tsx': None,
                        'product-rating.tsx': None,
                        'add-to-cart-button.tsx': None,
                        'add-to-wishlist-button.tsx': None,
                        'related-products.tsx': None,
                    },
                    'category': {
                        'index.ts': None,
                        'category-grid.tsx': None,
                        'category-card.tsx': None,
                        'category-filter.tsx': None,
                        'category-navigation.tsx': None,
                    },
                    'cart': {
                        'index.ts': None,
                        'cart-item.tsx': None,
                        'cart-summary.tsx': None,
                        'cart-drawer.tsx': None,
                        'mini-cart.tsx': None,
                        'cart-totals.tsx': None,
                    },
                    'checkout': {
                        'index.ts': None,
                        'checkout-form.tsx': None,
                        'checkout-steps.tsx': None,
                        'billing-form.tsx': None,
                        'shipping-form.tsx': None,
                        'payment-form.tsx': None,
                        'order-summary.tsx': None,
                        'order-confirmation.tsx': None,
                    },
                    'account': {
                        'index.ts': None,
                        'account-dashboard.tsx': None,
                        'profile-form.tsx': None,
                        'order-history.tsx': None,
                        'order-details.tsx': None,
                        'address-book.tsx': None,
                        'address-form.tsx': None,
                        'wishlist-grid.tsx': None,
                        'settings-form.tsx': None,
                    },
                    'common': {
                        'index.ts': None,
                        'search-results.tsx': None,
                        'pagination.tsx': None,
                        'product-filters.tsx': None,
                        'sort-dropdown.tsx': None,
                        'newsletter-signup.tsx': None,
                        'price-display.tsx': None,
                        'rating-stars.tsx': None,
                        'empty-state.tsx': None,
                    },
                },
                'admin': {
                    'index.ts': None,
                    'dashboard': {
                        'index.ts': None,
                        'stats-cards.tsx': None,
                        'sales-chart.tsx': None,
                        'revenue-chart.tsx': None,
                        'recent-orders.tsx': None,
                        'top-products.tsx': None,
                        'customer-activity.tsx': None,
                        'quick-actions.tsx': None,
                    },
                    'products': {
                        'index.ts': None,
                        'product-form.tsx': None,
                        'product-table.tsx': None,
                        'product-filters.tsx': None,
                        'product-image-upload.tsx': None,
                        'product-variants-form.tsx': None,
                        'product-seo-form.tsx': None,
                        'product-inventory-form.tsx': None,
                        'bulk-product-actions.tsx': None,
                        'product-import.tsx': None,
                        'product-export.tsx': None,
                    },
                    'categories': {
                        'index.ts': None,
                        'category-form.tsx': None,
                        'category-table.tsx': None,
                        'category-tree.tsx': None,
                        'category-image-upload.tsx': None,
                    },
                    'brands': {
                        'index.ts': None,
                        'brand-form.tsx': None,
                        'brand-table.tsx': None,
                        'brand-logo-upload.tsx': None,
                    },
                    'orders': {
                        'index.ts': None,
                        'order-table.tsx': None,
                        'order-details.tsx': None,
                        'order-status-form.tsx': None,
                        'order-timeline.tsx': None,
                        'order-items.tsx': None,
                        'order-actions.tsx': None,
                        'bulk-order-actions.tsx': None,
                    },
                    'customers': {
                        'index.ts': None,
                        'customer-table.tsx': None,
                        'customer-details.tsx': None,
                        'customer-form.tsx': None,
                        'customer-orders.tsx': None,
                        'customer-stats.tsx': None,
                    },
                    'users': {
                        'index.ts': None,
                        'user-form.tsx': None,
                        'user-table.tsx': None,
                        'role-selector.tsx': None,
                        'permissions-form.tsx': None,
                    },
                    'analytics': {
                        'index.ts': None,
                        'analytics-chart.tsx': None,
                        'sales-report.tsx': None,
                        'product-report.tsx': None,
                        'customer-report.tsx': None,
                        'date-range-picker.tsx': None,
                        'report-export.tsx': None,
                    },
                    'settings': {
                        'index.ts': None,
                        'general-settings-form.tsx': None,
                        'store-settings-form.tsx': None,
                        'shipping-settings-form.tsx': None,
                        'tax-settings-form.tsx': None,
                        'email-settings-form.tsx': None,
                        'seo-settings-form.tsx': None,
                        'security-settings-form.tsx': None,
                        'payment-settings-form.tsx': None,
                    },
                    'common': {
                        'index.ts': None,
                        'data-table.tsx': None,
                        'page-header.tsx': None,
                        'form-wrapper.tsx': None,
                        'image-upload.tsx': None,
                        'file-upload.tsx': None,
                        'rich-text-editor.tsx': None,
                        'bulk-actions.tsx': None,
                        'confirmation-dialog.tsx': None,
                        'export-button.tsx': None,
                    },
                },
                'addon-system': {
                    'index.ts': None,
                    'addon-manager.tsx': None,
                    'addon-card.tsx': None,
                    'addon-grid.tsx': None,
                    'addon-uploader.tsx': None,
                    'addon-installer.tsx': None,
                    'addon-settings.tsx': None,
                    'addon-marketplace.tsx': None,
                    'addon-details.tsx': None,
                    'addon-progress.tsx': None,
                    'addon-logs.tsx': None,
                    'hook-renderer.tsx': None,
                    'dynamic-component.tsx': None,
                    'dynamic-page.tsx': None,
                    'addon-provider.tsx': None,
                },
            },
            'lib': {
                'index.ts': None,
                'auth': {
                    'index.ts': None,
                    'config.ts': None,
                    'providers.ts': None,
                    'middleware.ts': None,
                    'session.ts': None,
                    'permissions.ts': None,
                },
                'database': {
                    'index.ts': None,
                    'connection.ts': None,
                    'models.ts': None,
                    'seed.ts': None,
                    'migrations.ts': None,
                },
                'utils': {
                    'index.ts': None,
                    'cn.ts': None,
                    'validation.ts': None,
                    'encryption.ts': None,
                    'email.ts': None,
                    'file-upload.ts': None,
                    'image.ts': None,
                    'seo.ts': None,
                    'currency.ts': None,
                    'date.ts': None,
                    'slug.ts': None,
                    'constants.ts': None,
                    'helpers.ts': None,
                },
                'addon-system': {
                    'index.ts': None,
                    'addon-manager.ts': None,
                    'addon-loader.ts': None,
                    'addon-installer.ts': None,
                    'addon-validator.ts': None,
                    'hook-system.ts': None,
                    'component-loader.ts': None,
                    'route-handler.ts': None,
                    'marketplace.ts': None,
                    'security.ts': None,
                    'types.ts': None,
                },
                'security': {
                    'index.ts': None,
                    'license-validator.ts': None,
                    'encryption.ts': None,
                    'rate-limiter.ts': None,
                    'csrf.ts': None,
                    'sanitization.ts': None,
                },
                'hooks': {
                    'index.ts': None,
                    'use-auth.ts': None,
                    'use-cart.ts': None,
                    'use-wishlist.ts': None,
                    'use-toast.ts': None,
                    'use-upload.ts': None,
                    'use-search.ts': None,
                    'use-pagination.ts': None,
                    'use-addons.ts': None,
                    'use-local-storage.ts': None,
                    'use-debounce.ts': None,
                    'use-api.ts': None,
                },
                'providers': {
                    'index.ts': None,
                    'auth-provider.tsx': None,
                    'theme-provider.tsx': None,
                    'cart-provider.tsx': None,
                    'toast-provider.tsx': None,
                    'addon-provider.tsx': None,
                    'app-provider.tsx': None,
                },
                'types': {
                    'index.ts': None,
                    'auth.ts': None,
                    'user.ts': None,
                    'product.ts': None,
                    'category.ts': None,
                    'brand.ts': None,
                    'order.ts': None,
                    'cart.ts': None,
                    'wishlist.ts': None,
                    'review.ts': None,
                    'coupon.ts': None,
                    'shipping.ts': None,
                    'tax.ts': None,
                    'settings.ts': None,
                    'addon.ts': None,
                    'api.ts': None,
                    'common.ts': None,
                },
            },
            'models': {
                'index.ts': None,
                'User.ts': None,
                'Product.ts': None,
                'ProductVariant.ts': None,
                'Category.ts': None,
                'Brand.ts': None,
                'Attribute.ts': None,
                'AttributeValue.ts': None,
                'Order.ts': None,
                'OrderItem.ts': None,
                'Cart.ts': None,
                'CartItem.ts': None,
                'Wishlist.ts': None,
                'WishlistItem.ts': None,
                'Review.ts': None,
                'Coupon.ts': None,
                'ShippingZone.ts': None,
                'ShippingMethod.ts': None,
                'TaxRate.ts': None,
                'Setting.ts': None,
                'EmailTemplate.ts': None,
                'Addon.ts': None,
                'AddonSetting.ts': None,
                'License.ts': None,
                'ActivityLog.ts': None,
            },
            'services': {
                'index.ts': None,
                'auth.service.ts': None,
                'user.service.ts': None,
                'product.service.ts': None,
                'category.service.ts': None,
                'brand.service.ts': None,
                'attribute.service.ts': None,
                'order.service.ts': None,
                'cart.service.ts': None,
                'wishlist.service.ts': None,
                'review.service.ts': None,
                'coupon.service.ts': None,
                'shipping.service.ts': None,
                'tax.service.ts': None,
                'email.service.ts': None,
                'upload.service.ts': None,
                'search.service.ts': None,
                'analytics.service.ts': None,
                'settings.service.ts': None,
                'addon.service.ts': None,
                'license.service.ts': None,
            },
            'config': {
                'index.ts': None,
                'database.ts': None,
                'auth.ts': None,
                'upload.ts': None,
                'email.ts': None,
                'addon.ts': None,
                'license.ts': None,
                'cache.ts': None,
                'app.ts': None,
            },
            'scripts': {
                'setup.js': None,
                'build.js': None,
                'seed.js': None,
                'validate-addon.js': None,
                'install-addon.js': None,
                'deploy.js': None,
                'backup.js': None,
            },
            'docs': {
                'README.md': None,
                'installation.md': None,
                'configuration.md': None,
                'api-reference.md': None,
                'addon-development.md': None,
                'deployment.md': None,
                'troubleshooting.md': None,
                'changelog.md': None,
            },
            'uploads': {
                '.gitkeep': None,
                'products': {},
                'categories': {},
                'brands': {},
                'users': {},
                'addons': {},
                'temp': {},
            },
            'installed-addons': {
                '.gitkeep': None,
            },
            'public': {
                'images': {
                    'logo.png': None,
                    'logo-dark.png': None,
                    'favicon.ico': None,
                    'placeholder-product.png': None,
                    'placeholder-avatar.png': None,
                    'setup': {
                        'welcome.png': None,
                        'database.png': None,
                        'admin.png': None,
                        'complete.png': None,
                    },
                },
                'icons': {
                    'icon-192x192.png': None,
                    'icon-512x512.png': None,
                    'apple-touch-icon.png': None,
                    'favicon-16x16.png': None,
                    'favicon-32x32.png': None,
                    'favicon.ico': None,
                },
                'addon-assets': {
                    '.gitkeep': None,
                },
                'sw.js': None,
            },
        },
    }

    def create_structure(base_path: Path, structure: dict):
        for name, content in structure.items():
            current_path = base_path / name
            if content is None:  # File
                current_path.parent.mkdir(parents=True, exist_ok=True)
                current_path.touch()
            elif isinstance(content, dict):  # Directory
                current_path.mkdir(parents=True, exist_ok=True)
                create_structure(current_path, content)

    # Create the project structure
    base_path = Path.cwd()
    create_structure(base_path, project_structure)
    print(f"Project structure created successfully at {base_path / 'ecommerce-platform-pro'}")

if __name__ == "__main__":
    create_project_structure()